# ============= Prompt =================

add_newline = false
command_timeout = 2000
format = """
$username$directory$git_branch$git_status$memory_usage$fill$cmd_duration
$battery$character"""

# ============= Modules ================

[battery]
charging_symbol = '⇡ '
discharging_symbol = '⇣ '
full_symbol = '• '
unknown_symbol = '• '

## Between 0% and 25%
[[battery.display]]
threshold = 25
style = 'bold red'

## Between 25% and 45%
[[battery.display]]
threshold = 45
style = 'bold yellow'

## Between 45% and 100%
[[battery.display]]
threshold = 100
style = 'bold green'

[character]
error_symbol = "[✗](red)"
success_symbol = "[➜](green)"

[cmd_duration]
format = '[$duration]($style) '
min_time = 1
style = "bright-blue"

[directory]
format = "in [$path]($style) "
style = "yellow"
truncate_to_repo = false
truncation_length = 2
truncation_symbol = "…/"

[fill]
symbol = ' '

[git_branch]
format = 'on [$branch]($style) '

[memory_usage]
disabled = false
format = '[${ram}( | ${swap})]($style) '

[username]
format = "[#](blue) [$user]($style) "
show_always = true
style_user = "cyan"
